import { Geist, Geist_Mono, Teko } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Layout/Navbar";
import Footer from "@/components/Layout/Footer";
import { Toaster } from "react-hot-toast";
import Chat from "@/components/Layout/Chat";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});



const teko = Teko({
  variable: "--font-teko",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
  
      <body
        className={` ${geistSans.variable} ${geistMono.variable} ${teko.variable} antialiased`}
      >

            <Navbar/>
        {children}
        <Chat/>
        <Toaster/>
      </body>
      <Footer/>
    </html>
  );
}
